#!/bin/sh

# clean up old files
rm ~/.zshrc
rm ~/.oh-my-zsh -rf

# install oh-my-zsh
yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# replace file generated by zsh and replace with correct config
rm ~/.zshrc

cd $(dirname "$0")
ln -s "$(pwd)/.zshrc" ~


# download plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
